import './config/env.js';import path from 'node:path';import {fileURLToPath} from 'node:url';import express from 'express';import cors from 'cors';import helmet from 'helmet';import morgan from 'morgan';import rateLimit from 'express-rate-limit';
import {connectDatabase,databaseStatus} from './services/database.service.js';import authRoutes from './routes/auth.js';import customerRoutes from './routes/customers.js';import conversationRoutes from './routes/conversations.js';import settingsRoutes from './routes/settings.js';import systemRoutes from './routes/system.js';import hermesRoutes from './routes/hermes.js';import whatsappRoutes from './routes/whatsapp.js';
const app=express();app.set('trust proxy',1);app.use(helmet({crossOriginResourcePolicy:false}));
const allowedOrigins=(process.env.CLIENT_ORIGIN||'http://localhost:5173').split(',').map(s=>s.trim()).filter(Boolean);
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.includes(origin))return cb(null,true);return cb(null,false);}}));
app.use(express.json({limit:'1mb'}));app.use(morgan('tiny'));app.use('/api',rateLimit({windowMs:60000,max:240,standardHeaders:true,legacyHeaders:false}));
app.get('/api/health',(req,res)=>res.status(databaseStatus()==='CONNECTED'?200:503).json({service:'Customer AI',status:databaseStatus()==='CONNECTED'?'healthy':'degraded',mongodb:databaseStatus()}));app.use('/api/auth',authRoutes);app.use('/api/customers',customerRoutes);app.use('/api/conversations',conversationRoutes);app.use('/api/settings',settingsRoutes);app.use('/api/system',systemRoutes);app.use('/api/hermes',hermesRoutes);app.use('/api/whatsapp',whatsappRoutes);app.use((err,req,res,next)=>{if(err.name==='CastError')return res.status(400).json({error:{message:'Invalid resource identifier.'}});console.error(err);res.status(err.status||500).json({error:{message:err.message||'Unexpected server error.'}})});
const clientDist=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../client/dist');app.use(express.static(clientDist));app.get(/^(?!\/api).*/,(_,res)=>res.sendFile(path.join(clientDist,'index.html')));
const port=process.env.PORT||5000;const host=process.env.HOST||'127.0.0.1';connectDatabase().then(()=>app.listen(port,host,()=>console.log(`Customer AI API listening on ${host}:${port}`))).catch(error=>{console.error(`MongoDB connection failed: ${error.message}`);app.listen(port,host,()=>console.log(`Customer AI API listening in degraded mode on ${host}:${port}`))});
